config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#home'

  get 'visitor/:id', to: 'visitors#show', as: 'visitor'
  get 'visitors', to: 'visitors#index'
  get 'visitors/new', to: 'visitors#new', as: 'new_visitors'
  post 'visitors', to: 'visitors#create'
  get 'visitors/:id/edit', to: 'visitors#edit', as: 'visitor_edit'
  put 'visitor/:id', to: 'visitors#update'

end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def home
    render :home
  end

  def new
    @visitor = Visitor.new 
    render :new 
  end

  def index
    @visitors = Visitor.all 
    render :index
  end 

  def create
    @visitor = Visitor.create(visitor_params)
    redirect_to :root
  end
 

  private

  def visitor_params
    params.require(:visitor).permit(:first_name, :last_name, :phone_number, :street_address, :city, :state, :date_of_visit, :referral)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Visitor Management System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
 <body>
 <div class="container">
  <div class="row">
    <h1> Welcome to Lirio de los Valles Visitors Management </h1>
  </div>
  <div class="supporting">
    <div class="container">
      <div class="col">
        <ul><%= link_to "Add Visitor", new_visitors_path, class: "btn-default" %></ul>
        <ul><%= link_to "View All Visitors", visitors_path, class: "btn-default" %></ul>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>

  <div class="footer">
    <div class="container">
      <p>&copy; Lirio de los Valles 2015</p>
    </div>
  </div>
</div>
<%= yield %>
 </div>
 </body>
</html>

app/views/visitors/_form.html.erb
<%= form_for @visitor, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= f.label :first_name %> <br>
  <%= f.text_field :first_name %>
  <br/>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %>
  <br/>
  <%= f.label :phone_number %><br>
  <%= f.text_field :phone_number %>
  <br/>
  <%= f.label :street_address %><br>
  <%= f.text_field :street_address %>
  <br/>
  <%= f.label :city %><br>
  <%= f.text_field :city %>
  <br/>
  <%= f.label :state %><br>
  <%= f.text_field :state %>
  <br/>
  <%= f.label :date_of_visit %><br>
  <%= f.text_field :date_of_visit %>
  <br/>
  <%= f.label :referral %><br>
  <%= f.text_field :referral %>
  <br/>
  <%= f.submit "Add New Visitor" %>
<% end %>

app/views/visitors/_visitor.html.erb
<div class="visitor">
  <h2><%= visitor.first_name %></h2>
  <h2><%= visitor.last_name %></h2>
  <h2><%= visitor.phone_number %></h2>


</div>

app/views/visitors/home.html.erb
<div class="visitors">
  
</div>

app/views/visitors/index.html.erb
<div class="visitors">
  <% @visitors.each do |visitor| %>
    <%= render partial: "visitor", object: visitor %>
  <% end %>
</div>

app/views/visitors/new.html.erb
<h2>New Vistor</h2>

<%= render "form" %>

<br/>
<div>
  <%= link_to "Back", :back %>
</div>